### ISSUE TITLE
Concurrent or nearly concurrent access

### ISSUE THREAD

**Issue by darrepac** [ccutrer/balboa_worldwide_app#19]
Hi

I would like opinion of other.
Configuration:
- Balboa spa with Wifi option
- Balboa app
- Python script to acess my spa through domoticz

Sometimes I saw that some orders are not sent to the spa. I dive into the cli python version and indeed sometimes it won't simply connect to the spa (timeout).
After several trials my feeling is that it works well if I did not connect with Balboa app before.
If I did not use Balboa app for 5-10min, it works
If I did use Balboa app before (for example to check if the command is being sent), it fails.
My feeling is that it also happens the other way around: if I send a command with my Python script and then try to connect with Balboa app in local, it fails...

So it is like the wifi module avoid concurrent access.
Does anybody has got the same feeling?

**Comment by ccutrer** [comment]
This is exactly correct - the wifi module only allows one concurrent connection. I also found that it uses a somewhat standard discovery method that _something_ on my network was seeing it and constantly trying to connect, effectively locking out either the app or any automation stuff. I've been much happier since I cut the wifi module out of the loop and connect directly via RS-485.
