### ISSUE TITLE
Does the BWA work with mesh networks?

### ISSUE THREAD

**Issue by winzig** [ccutrer/balboa_worldwide_app#67]
Getting a spa installed and asked about WiFi/app control, and they indicated they could install the "Balboa Worldwide" wifi module. After looking at their official app in the App Store, a sense of dread came over me 😂, and began wondering if they might have an API for the device instead, for direct access... and now grateful to see this repo. 

One question though, are folks here successfully using the Balboa Worldwide Wifi on mesh networks? I have a Deco 6 system at my house (mesh wifi) and then I noticed this note on Balboa's site:

> *Note: Mesh routers will not work with BWA™.

I've never run into a WiFi device that doesn't support the mesh wifi network we have, so was kind of taken aback. 

Anyone having issues using it on mesh networks, or know why they would have this warning? Are they using really ancient wifi hardware?

**Comment by ccutrer** [comment]
Usually such warnings are indicative of using early ESP8266 devices that simply connect to the first base station they see for the correct SSID, instead of the base station with the strongest signal. I haven't used WiFi in many many years because their WiFi module was so unreliable.  I doubt they've ever updated it. If you already have a spa with wifi, it's worth trying. If you don't have the WiFi module already, don't bother with it, and put a Raspberry Pi Zero W with a a USB RS485 adapter in your spa, using the serial bus. It's probably a little bit cheaper depending on what they're charging for the WiFi module, and definitely more reliable. If you're _really_ lucky or well-planned, you might be able to run a hardwired 22/2 to your spa for your RS485 indoors to something that's already on your network. Then no wireless is involved at all.
