### ISSUE TITLE
This solution and BalboaWiFi (ControlMySpa) parallel?

### ISSUE THREAD

**Issue by Stefan-83** [ccutrer/balboa_worldwide_app#80]
Hi,

I’m wondering if I could use this solution and BalboaWiFi (ControlMySpa) in parallel ?
Is this using the same cable like the official wifi adapter?

**Comment by ccutrer** [comment]
Yes, it uses the same connection as the official WiFi adapter. As long as you're using a Y-adapter to let both be connected at the same time, it should work just fine. It's been many years since I've used the official adapter. It may still be possible to just point this gem at the WiFi adapter and integrate over IP rather than a dedicated serial connection, though.
